services:
  # Backend service
  - type: web
    name: health-center-api
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false

  # Frontend service
  - type: web
    name: health-center-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html